---
title: "Cleaning Data"
author: "Clayton Chan"
date: "2024-10-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("DataScience_salaries_2024.csv")
head(df)
```
```{r}
sum(complete.cases(df)) == nrow(df) #Check for NA Values TRUE means there is none
df <- unique(df) #Get rid of duplicate observations 
```

```{r}
library(tidyverse)
table(df$employment_type)
df <- filter(df,employment_type == 'FT') # We will focus on full time salaries
```
```{r}
table(df$work_year) #Too few observations in 2020-2022 so we'll combine them into "Pandemic Era"
df$work_year <- ifelse(df$work_year == 2024, "2024",
                ifelse(df$work_year == 2023, "2023", "Pandemic"))
df$work_year <- factor(df$work_year,levels = c("Pandemic","2023","2024"), ordered = TRUE)
#Relevel
```
```{r}
table(df$experience_level)
df$experience_level <- factor(df$experience_level, levels = c("EN","MI","SE","EX"), ordered = T) #Relevel
```

```{r}
df <- select(df,-c("employment_type","salary","salary_currency","employee_residence"))
#Get rid of employment type as every observation is full time
#Get rid of salary and currency as we have the salary in USD
#Get rid of employee residene as we already have the company location and the company location 
#matters more for predicting the salary
```

```{r}
table(df$remote_ratio)
table(df$company_size)
df$company_size <- factor(df$company_size,levels = c("S","M","L"), ordered = TRUE)
```
```{r}
df$remote_ratio <- car::recode(df$remote_ratio,"0='In-Person';50='Hybrid';100='Remote'")
df$remote_ratio <- factor(df$remote_ratio, levels = c("In-Person","Hybrid","Remote"))
```

```{r}
library(countrycode)
df$company_location <- countrycode(df$company_location, origin = "iso2c", destination = "country.name")
table(df$company_location)

developed_countries <- c("Andorra","Australia","Austria","Belgium","Canada","Croatia","Czechia","Denmark","Estonia","Finland","France","Germany","Gibraltar","Greece","Hong Kong SAR China","Ireland","Israel","Italy","Japan","Latvia","Lithuania","Luxembourg","Malta","Netherlands","New Zealand","Norway","Portugal","Singapore","Slovenia","South Korea","Spain","Sweden","Switzerland","United Kingdom")

df$company_location <- ifelse(df$company_location == "United States", "US",
                       ifelse(df$company_location %in% developed_countries,"First World","Developing"))
#Combine all first world countries into developed label leaving the rest as the developing countries
df$company_location <- factor(df$company_location, levels = c("US","First World","Developing"))
```
```{r}
titles <- names(table(df$job_title))
analyst <- c(titles[c(1,40,44:51,67,75,78,93,103:104,109,126,134,139,148)])
scientist <- c(titles[c(13,79:89,99,106,111,125,128,137,149)])
mle <- c(titles[c(14:15,107,112:123,129:131,138)])
engineer <- c(titles[c(20,27,38:39,54:56,58,69,72,76,94,110,127,136,147,150)])
BI <- c(titles[c(21:24,28:36,133)])
df$job_title <- ifelse(df$job_title %in% analyst, "DA",
                ifelse(df$job_title %in% scientist,"DS",
                ifelse(df$job_title %in% engineer, "DE",
                ifelse(df$job_title %in% mle,"ML",
                ifelse(df$job_title %in% BI,"BI","Other")))))
df$job_title <- relevel(factor(df$job_title), ref = "DA")
#Condense all titles with data science in the name to data scientist and repeat for analysts, MLE and etc
```

```{r}
df
```

